import React,{useEffect,useRef,useState}from 'react'
import {createRoot} from 'react-dom/client'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import {supabase,type BusLocation} from './lib/supabase'
import './styles.css'
type Role='driver'|'passenger'; type Screen='home'|'auth'|'map'
function App(){
 const [screen,setScreen]=useState<Screen>('home'),[role,setRole]=useState<Role>('passenger'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[bus,setBus]=useState<BusLocation|null>(null),[sharing,setSharing]=useState(false)
 const el=useRef<HTMLDivElement>(null),map=useRef<maplibregl.Map|null>(null),userMarker=useRef<maplibregl.Marker|null>(null),busMarker=useRef<maplibregl.Marker|null>(null),watch=useRef<number|null>(null)
 useEffect(()=>{if(screen!=='map'||!el.current||map.current)return;map.current=new maplibregl.Map({container:el.current,style:'https://demotiles.maplibre.org/style.json',center:[-42.64,-19.58],zoom:13,attributionControl:false});map.current.addControl(new maplibregl.NavigationControl(),'bottom-right');return()=>{map.current?.remove();map.current=null}},[screen])
 useEffect(()=>{if(screen!=='map')return;const c=supabase.channel('bus-live').on('postgres_changes',{event:'*',schema:'public',table:'bus_locations'},p=>setBus(p.new as BusLocation)).subscribe();supabase.from('bus_locations').select('*').eq('is_active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>setBus(data));return()=>{supabase.removeChannel(c)}},[screen])
 useEffect(()=>{if(!bus||!map.current)return;const node=document.createElement('div');node.className='bus-pin';node.textContent='🚌';if(!busMarker.current)busMarker.current=new maplibregl.Marker({element:node}).setLngLat([bus.longitude,bus.latitude]).addTo(map.current);else busMarker.current.setLngLat([bus.longitude,bus.latitude])},[bus])
 function showPosition(publish=false){navigator.geolocation.getCurrentPosition(async({coords})=>{const pos:[number,number]=[coords.longitude,coords.latitude];map.current?.flyTo({center:pos,zoom:16});const node=document.createElement('div');node.className='user-pin';if(!userMarker.current)userMarker.current=new maplibregl.Marker({element:node}).setLngLat(pos).addTo(map.current);else userMarker.current.setLngLat(pos);if(publish)await supabase.from('bus_locations').upsert({id:'00000000-0000-0000-0000-000000000001',route_name:'Ônibus em operação',latitude:coords.latitude,longitude:coords.longitude,accuracy:coords.accuracy,is_active:true,updated_at:new Date().toISOString()})},()=>setMessage('Permita o GPS no navegador para usar o mapa.'),{enableHighAccuracy:true})}
 function toggle(){if(sharing){if(watch.current)navigator.geolocation.clearWatch(watch.current);setSharing(false);return}showPosition(true);watch.current=navigator.geolocation.watchPosition(({coords})=>supabase.from('bus_locations').upsert({id:'00000000-0000-0000-0000-000000000001',route_name:'Ônibus em operação',latitude:coords.latitude,longitude:coords.longitude,accuracy:coords.accuracy,is_active:true,updated_at:new Date().toISOString()}),()=>setMessage('Não foi possível manter o GPS ativo.'),{enableHighAccuracy:true,maximumAge:5000});setSharing(true)}
 async function signIn(e:React.FormEvent){e.preventDefault();setMessage('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return setMessage('E-mail ou senha inválidos.');setScreen('map')}
 async function signUp(){const {error}=await supabase.auth.signUp({email,password,options:{data:{role}}});setMessage(error?error.message:'Cadastro realizado. Verifique seu e-mail para confirmar.')}
 if(screen==='home')return <main className="app"><header className="top"><span className="brand">GPS BUS</span><span className="live">AO VIVO</span></header><section className="hero"><div className="bus">🚌</div><h1>GPS BUS</h1><p>Rastreamento em tempo real</p></section><button className="choice" onClick={()=>{setRole('driver');setScreen('auth')}}><span className="circle">🛡️</span><span><strong>Motorista</strong><small>Compartilhe a localização do ônibus</small></span><span className="chev">›</span></button><button className="choice" onClick={()=>{setRole('passenger');setScreen('auth')}}><span className="circle">◉</span><span><strong>Passageiro</strong><small>Acompanhe o ônibus e sua posição</small></span><span className="chev">›</span></button></main>
 if(screen==='auth')return <main className="app auth"><button className="back" onClick={()=>setScreen('home')}>×</button><div className="role">{role==='driver'?'🛡️':'◉'}</div><h1>Entrar como<br/>{role==='driver'?'motorista':'passageiro'}</h1><p className="muted">Use sua conta para acessar o GPS BUS.</p><form onSubmit={signIn}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<p>{message}</p>}<button className="primary">Entrar</button></form><button className="link" onClick={signUp}>Criar uma conta</button></main>
 return <main className="app tracker"><div className="map" ref={el}/><header className="header"><button onClick={()=>{if(watch.current)navigator.geolocation.clearWatch(watch.current);setScreen('home')}}>‹</button><b>GPS BUS</b><span>{role==='driver'?'MOTORISTA':'PASSAGEIRO'}</span></header><section className="status"><span className="circle">🚌</span><div><strong>{bus?.route_name||'Aguardando ônibus'}</strong><small>{bus?('Atualizado agora • precisão '+Math.round(bus.accuracy||0)+' m'):'Nenhuma localização compartilhada ainda'}</small></div>{bus&&<i className="online"/>}</section><div className="actions">{role==='driver'?<button className={sharing?'stop':'primary'} onClick={toggle}>{sharing?'Parar rastreamento':'Iniciar rastreamento'}</button>:<button className="primary" onClick={()=>showPosition()}>Minha localização</button>}<button className="outline" onClick={()=>bus&&map.current?.flyTo({center:[bus.longitude,bus.latitude],zoom:16})}>Ver ônibus</button></div>{message&&<p className="status">{message}</p>}</main>
}
createRoot(document.getElementById('root')!).render(<App/>)
